$template = Get-Content -Raw "template.html"

Function Generate-Package {
    param($filename, $title, $duration, $region, $places, $type, $bg, $overview, $price, $price_tax, $departing, $cities, $itinerary)

    $city_widgets = ""
    foreach ($c in $cities) {
        $cName = $c.Name
        $cNights = $c.Nights
        $city_widgets += "<div style='flex:1; text-align:center; min-width:80px;'><div style='font-size:1.6rem; margin-bottom:6px;'>📍</div><div style='font-weight:700; color:var(--navy); font-size:0.9rem;'>$cName</div><div style='font-size:0.78rem; color:var(--text-light);'>$cNights</div></div>"
    }

    $itinerary_html = ""
    $day = 1
    foreach ($i in $itinerary) {
        $iTitle = $i.Title
        $iDest = $i.Dest
        $iContent = $i.Content
        $itinerary_html += "<div class='itinerary-item'><div class='day-marker'>$day</div><div class='day-header'><h3 class='day-title'>$iTitle</h3><span class='day-dest'>$iDest</span></div><div class='day-content'>$iContent</div></div>"
        $day++
    }

    $html = $template.Replace("{{package_title}}", $title).Replace("{{duration}}", $duration).Replace("{{region}}", $region).Replace("{{places}}", $places).Replace("{{type}}", $type).Replace("{{bg_image}}", $bg).Replace("{{overview}}", $overview).Replace("{{city_widgets}}", $city_widgets).Replace("{{itinerary_html}}", $itinerary_html).Replace("{{price}}", $price).Replace("{{price_tax}}", $price_tax).Replace("{{departing}}", $departing)

    [System.IO.File]::WriteAllText("c:\Users\sai\Desktop\travelspark\packages\$filename", $html, [System.Text.Encoding]::UTF8)
    Write-Host "Created $filename"
}

Generate-Package -filename "andaman-package.html" -title "Enchanting Andaman" -duration "5 Nights / 6 Days" -region "Andaman" -places "Port Blair, Havelock" -type "Beaches Leisure" -bg "https://images.unsplash.com/photo-1588602641570-5b5ea6c4bcba?w=1800" -overview "Experience the pristine beaches, azure waters, and rich colonial history of the Andaman Islands. This 6-day tour covers the top attractions in Port Blair and the breathtaking Radhanagar Beach in Havelock Island." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Port Blair" -cities @(@{Name="Port Blair"; Nights="3 Nights"},@{Name="Havelock"; Nights="2 Nights"}) -itinerary @(@{Title="Arrival at Port Blair"; Dest="Port Blair"; Content="Arrive in Port Blair, the capital city. Check into your hotel. In the afternoon, visit the historic Cellular Jail followed by the moving Light Sound Show in the evening. Overnight at Port Blair."},@{Title="Port Blair to Havelock - Radhanagar Beach"; Dest="Havelock"; Content="Post breakfast, board a ferry to Havelock Island. Check-in to your hotel. Visit the world-famous Radhanagar Beach, known for its white sand and breathtaking sunset. Overnight at Havelock."},@{Title="Elephant Beach Excursion"; Dest="Havelock"; Content="Morning trip to Elephant Beach, famous for its coral reefs and water sports. Enjoy snorkeling. Return to hotel. Overnight at Havelock."},@{Title="Return to Port Blair"; Dest="Port Blair"; Content="Check out from Havelock and board the ferry back to Port Blair. Evening at leisure for shopping or relaxing at the hotel. Overnight at Port Blair."},@{Title="Ross Island"; Dest="Port Blair"; Content="Enjoy a full-day excursion to Ross Island and North Bay (Coral Island) offering excellent snorkeling opportunities. Overnight at Port Blair."},@{Title="Departure"; Dest="Port Blair"; Content="After breakfast, check out from the hotel and proceed to the airport for your return flight with infinite memories of the islands."})

Generate-Package -filename "do-dham-yatra-kedarnath.html" -title "Do Dham Yatra with Kedarnath Helicopter" -duration "5 Nights / 6 Days" -region "Uttarakhand" -places "Haridwar, Guptkashi, Kedarnath, Badrinath" -type "Pilgrimage" -bg "https://images.unsplash.com/photo-1627885233076-7cb058e5a31a?w=1800" -overview "Embark on a divine spiritual journey to the sacred shrines of Kedarnath and Badrinath. Experience the majesty of the Himalayas while seeking blessings. Includes a premium helicopter ride to Kedarnath for convenience." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Haridwar / Dehradun" -cities @(@{Name="Guptkashi"; Nights="2 Nights"},@{Name="Kedarnath"; Nights="1 Night"},@{Name="Badrinath"; Nights="1 Night"},@{Name="Rudraprayag"; Nights="1 Night"}) -itinerary @(@{Title="Haridwar - Guptkashi"; Dest="Guptkashi"; Content="Start your journey towards Guptkashi via Devprayag and Rudraprayag. Arrive, check-in to your hotel, and relax for the evening. Overnight stay at Guptkashi."},@{Title="Guptkashi - Kedarnath (By Helicopter)"; Dest="Kedarnath"; Content="Proceed to the Helipad for a flight to Kedarnath. Arrive at Kedarnath, check-in to your accommodation, and visit the sacred Kedarnath Temple for Darshan. Overnight stay at Kedarnath."},@{Title="Kedarnath - Guptkashi"; Dest="Guptkashi"; Content="After morning Darshan, return to the Helipad to fly back to Guptkashi. Spend the rest of the day at leisure reflecting on the spiritual experience. Overnight stay at Guptkashi."},@{Title="Guptkashi - Badrinath"; Dest="Badrinath"; Content="Drive to Badrinath via Joshimath. Upon arrival, check-in to the hotel. Take a holy dip in Tapt Kund followed by Darshan of Badrivishal. Overnight stay at Badrinath."},@{Title="Badrinath - Rudraprayag"; Dest="Rudraprayag"; Content="Visit Mana Village, Vyas Gufa, and Mata Murti Temple in the morning. Later, drive down to Rudraprayag / Srinagar for the night check-in. Overnight stay."},@{Title="Rudraprayag - Haridwar"; Dest="Haridwar"; Content="Drive back to Haridwar via Rishikesh. Visit Ram Jhula and Laxman Jhula if time permits. Tour concludes upon arrival in Haridwar."})

Generate-Package -filename "essence-of-kerala.html" -title "Essence of Kerala" -duration "4 Nights / 5 Days" -region "Kerala" -places "Munnar, Thekkady, Alleppey" -type "Family Nature" -bg "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1800" -overview "Discover the true essence of Gods Own Country. Wind through the sprawling tea gardens of Munnar, experience the spice plantations and wildlife of Thekkady, and cruise the tranquil backwaters of Alleppey in your private houseboat." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Kochi (Cochin)" -cities @(@{Name="Munnar"; Nights="2 Nights"},@{Name="Thekkady"; Nights="1 Night"},@{Name="Alleppey"; Nights="1 Night"}) -itinerary @(@{Title="Arrival at Cochin Drive to Munnar"; Dest="Munnar"; Content="Arrive at Cochin Airport/Station. Meet our representative and drive to Munnar, enjoying scenic waterfalls and tea gardens en route. Check-in to the hotel. Overnight stay at Munnar."},@{Title="Munnar Sightseeing"; Dest="Munnar"; Content="Post breakfast, go for a full day sightseeing of Munnar. Visit Mattupetty Dam, Echo Point, Tea Museum, and Eravikulam National Park. Return to hotel for overnight stay."},@{Title="Munnar to Thekkady"; Dest="Thekkady"; Content="Drive to Thekkady. Check-in to your hotel. Later, visit spice plantations or take an optional boat ride in Periyar Lake to spot wildlife. Overnight stay at Thekkady."},@{Title="Thekkady to Alleppey (Houseboat)"; Dest="Alleppey"; Content="Drive to Alleppey, the Venice of the East. Board your traditional houseboat at noon. Enjoy a scenic cruise through the backwaters, taking in village life. Meals served on board. Overnight stay in Houseboat."},@{Title="Departure from Cochin"; Dest="Cochin"; Content="After breakfast on the houseboat, disembark and drive back to Cochin for your return flight/train journey."})

Generate-Package -filename "fascinating-gujarat.html" -title "Fascinating Gujarat" -duration "6 Nights / 7 Days" -region "Gujarat" -places "Ahmedabad, Dwarka, Somnath, Sasan Gir" -type "Heritage Wildlife" -bg "https://images.unsplash.com/photo-1620612261623-0182fcff27a3?w=1800" -overview "Experience the vibrant culture, rich heritage, and spiritual aura of Gujarat. Visit the magnificent temples of Dwarka and Somnath, explore Gandhis ashram in Ahmedabad, and spot majestic Asiatic Lions in Gir National Park." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Ahmedabad" -cities @(@{Name="Ahmedabad"; Nights="1 Night"},@{Name="Dwarka"; Nights="2 Nights"},@{Name="Somnath"; Nights="1 Night"},@{Name="Sasan Gir"; Nights="1 Night"}) -itinerary @(@{Title="Arrival in Ahmedabad"; Dest="Ahmedabad"; Content="Arrive at Ahmedabad and check in. Visit Gandhi Ashram, Akshardham Temple and Adalaj Stepwell. Overnight at Ahmedabad."},@{Title="Ahmedabad to Dwarka"; Dest="Dwarka"; Content="Drive to Dwarka. Upon arrival, check in and later attend the evening Aarti at the famous Dwarkadhish Temple. Overnight at Dwarka."},@{Title="Dwarka Sightseeing"; Dest="Dwarka"; Content="Visit Bet Dwarka, Nageshwar Jyotirlinga, and the Rukmini Temple. Spend the evening at Gomti Ghat. Overnight at Dwarka."},@{Title="Dwarka to Somnath via Porbandar"; Dest="Somnath"; Content="Drive to Somnath. En route stop at Porbandar to visit Kirti Mandir. Arrive at Somnath, visit the Somnath Temple and enjoy the evening Sound and Light show. Overnight at Somnath."},@{Title="Somnath to Sasan Gir"; Dest="Sasan Gir"; Content="Drive a short distance to Sasan Gir, the home of the Asiatic Lion. Check into your wildlife resort and relax or take an afternoon jungle safari. Overnight at Gir."},@{Title="Sasan Gir to Ahmedabad"; Dest="Ahmedabad"; Content="Early morning safari (optional). After breakfast, drive back to Ahmedabad. Check in and relax for the evening. Overnight at Ahmedabad."},@{Title="Departure"; Dest="Ahmedabad"; Content="After breakfast, transfer to Ahmedabad airport/station for your onward journey."})

Generate-Package -filename "goa-escape-neelam.html" -title "Goa Escape (Neelam The Grand)" -duration "3 Nights / 4 Days" -region "Goa" -places "North Goa" -type "Leisure Beaches" -bg "https://images.unsplash.com/photo-1549893072-4bc678117f45?w=1800" -overview "A rejuvenating short break in the party capital of India. Stay in a premium property, relax by the pool, explore pristine beaches of North Goa, and indulge in amazing coastal cuisine." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Goa (Dabolim/Mopa)" -cities @(@{Name="Goa"; Nights="3 Nights"}) -itinerary @(@{Title="Arrival in Goa"; Dest="Goa"; Content="Arrive in Goa. Our representative will transfer you to your hotel (Neelam The Grand or similar). Rest of the day is at leisure to explore the nearby beaches. Overnight at hotel."},@{Title="North Goa Sightseeing"; Dest="Goa"; Content="Post breakfast, proceed for a half-day tour of North Goa visiting Fort Aguada, Calangute Beach, and Baga Beach. Evening at leisure. Overnight at hotel."},@{Title="Day at Leisure"; Dest="Goa"; Content="Enjoy a full day of leisure. Rent a two-wheeler, visit shacks, try water sports, or simply relax by the hotel pool. Overnight at hotel."},@{Title="Departure"; Dest="Goa"; Content="After breakfast, check out from the hotel and proceed to the Airport for your onward journey."})

Generate-Package -filename "karnataka-explorer.html" -title "Karnataka Explorer" -duration "9 Nights / 10 Days" -region "Karnataka" -places "Bangalore, Mysore, Hassan, Hospet, Badami" -type "Heritage" -bg "https://images.unsplash.com/photo-1600100397608-f010f41ab446?w=1800" -overview "A comprehensive 10-day tour exploring the rich cultural heritage and magnificent ancient temples of Karnataka. From the grand Mysore Palace to the impressive ruins of Hampi and architectural marvels of Badami." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Bangalore" -cities @(@{Name="Bangalore"; Nights="1 Night"},@{Name="Mysore"; Nights="2 Nights"},@{Name="Hassan"; Nights="2 Nights"},@{Name="Hospet"; Nights="2 Nights"},@{Name="Badami"; Nights="2 Nights"}) -itinerary @(@{Title="Arrival in Bangalore"; Dest="Bangalore"; Content="Arrive in Bangalore. Transfer to hotel. Afternoon sightseeing including Lal Bagh Botanical Gardens and Vidhana Soudha. Overnight in Bangalore."},@{Title="Bangalore to Mysore"; Dest="Mysore"; Content="Drive to Mysore. En route visit Srirangapatna. Check in to the hotel and later visit the majestic Mysore Palace. Overnight in Mysore."},@{Title="Mysore Sightseeing"; Dest="Mysore"; Content="Full day tour visiting Chamundi Hill, St. Philomenas Church, and Brindavan Gardens in the evening. Overnight in Mysore."},@{Title="Mysore to Hassan"; Dest="Hassan"; Content="Drive to Hassan. En route visit Shravanabelagola to see the Gommateshwara statue. Arrive and check in. Overnight in Hassan."},@{Title="Belur Halebid Excursion"; Dest="Hassan"; Content="Visit the stunning Hoysala temples of Belur and Halebid, famous for their intricate carvings. Return to Hassan for overnight stay."},@{Title="Hassan to Hospet (Hampi)"; Dest="Hospet"; Content="Long scenic drive to Hospet, the gateway to Hampi. Check in and relax. Overnight in Hospet."},@{Title="Exploring Hampi Ruins"; Dest="Hospet"; Content="Full day exploring the UNESCO World Heritage site of Hampi. Visit the Virupaksha Temple, Vittala Temple, and Royal Enclosure. Overnight in Hospet."},@{Title="Hospet to Badami"; Dest="Badami"; Content="Drive to Badami. Check in to the hotel. Visit the famous rock-cut cave temples of Badami in the afternoon. Overnight in Badami."},@{Title="Pattadakal Aihole Excursion"; Dest="Badami"; Content="Visit the ancient temple complexes of Aihole and Pattadakal (UNESCO site), showcasing early Chalukyan architecture. Overnight in Badami."},@{Title="Departure from Hubli/Belgaum"; Dest="Hubli"; Content="After breakfast, drive to Hubli or Belgaum airport/station for your onward journey."})

Generate-Package -filename "kashmir-heaven-on-earth.html" -title "Kashmir - Heaven on Earth" -duration "5 Nights / 6 Days" -region "Kashmir" -places "Srinagar, Gulmarg, Pahalgam" -type "Family Romance" -bg "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=1800" -overview "Experience the unparalleled beauty of Paradise on Earth. Enjoy a Shikara ride on Dal Lake, witness the snow-capped peaks of Gulmarg, and stroll through the lush green valleys of Pahalgam." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Srinagar" -cities @(@{Name="Srinagar"; Nights="2 Nights"},@{Name="Pahalgam"; Nights="2 Nights"},@{Name="Srinagar"; Nights="1 Night"}) -itinerary @(@{Title="Arrival in Srinagar"; Dest="Srinagar"; Content="Arrive at Srinagar airport. Meet our representative and transfer to the hotel. Later, visit the famous Mughal Gardens. Overnight at Srinagar hotel."},@{Title="Srinagar to Pahalgam"; Dest="Pahalgam"; Content="Drive to Pahalgam via saffron fields at Pampore. Arrive and check-in. Enjoy the scenic beauty. Overnight at Pahalgam."},@{Title="Pahalgam Sightseeing"; Dest="Pahalgam"; Content="Day at leisure to explore Pahalgam. Optionally visit Betaab Valley, Aru Valley, and Chandanwari. Overnight at Pahalgam."},@{Title="Pahalgam to Gulmarg Day Trip"; Dest="Srinagar"; Content="Drive to Gulmarg. Enjoy the famous Gondola ride. Later return to Srinagar for an overnight stay."},@{Title="Srinagar - Houseboat Stay"; Dest="Srinagar"; Content="Check into a traditional Houseboat on Dal Lake. In the afternoon, enjoy a relaxing Shikara Ride on the lake. Overnight in Houseboat."},@{Title="Departure"; Dest="Srinagar"; Content="After breakfast, transfer to Srinagar airport for your onward flight."})

Generate-Package -filename "ladakh-delight.html" -title "Ladakh Delight" -duration "5 Nights / 6 Days" -region "Ladakh" -places "Leh, Nubra Valley, Pangong Tso" -type "Adventure Scenic" -bg "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=1800" -overview "A thrilling expedition to the land of high passes. Drive through Khardung La, the highest motorable road, ride the double-humped camels in Nubra Valley, and camp by the mesmerizing blue waters of Pangong Lake." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. inner line permits GST" -departing "Leh" -cities @(@{Name="Leh"; Nights="3 Nights"},@{Name="Nubra Valley"; Nights="1 Night"},@{Name="Pangong"; Nights="1 Night"}) -itinerary @(@{Title="Arrival in Leh"; Dest="Leh"; Content="Arrive in Leh and transfer to hotel. Rest of the day is crucial for acclimatization to the high altitude. Late afternoon visit to Shanti Stupa. Overnight in Leh."},@{Title="Leh Local / Sham Valley"; Dest="Leh"; Content="Drive towards Sham Valley. Visit Hall of Fame, Magnetic Hill, Gurudwara Pathar Sahib, and Sangam. Overnight in Leh."},@{Title="Leh to Nubra Valley via Khardung La"; Dest="Nubra Valley"; Content="Drive to Nubra Valley via Khardung La Pass. Arrive at Hunder. Check into camps. Enjoy a ride on the bactrian camel. Overnight in Nubra."},@{Title="Nubra to Pangong Tso via Shyok"; Dest="Pangong"; Content="After breakfast, visit Diskit Monastery. Later drive to Pangong Lake via the Shyok river route. Overnight in camps at Pangong."},@{Title="Pangong to Leh via Chang La"; Dest="Leh"; Content="Wake up to a beautiful sunrise at Pangong. Later drive back to Leh passing through Chang La pass. Evening free for shopping in Leh market. Overnight in Leh."},@{Title="Departure"; Dest="Leh"; Content="Early morning transfer to Leh airport to board your flight back home."})

Generate-Package -filename "northeast-odyssey.html" -title "Northeast Odyssey" -duration "6 Nights / 7 Days" -region "North-East" -places "Guwahati, Shillong, Cherrapunjee" -type "Nature Culture" -bg "https://images.unsplash.com/photo-1596788062835-263be0b82eb9?w=1800" -overview "Explore the pristine beauty of Northeast India. Ascend into the clouds in Meghalaya, marvel at living root bridges in Cherrapunjee, and cruise the mighty Brahmaputra river in Assam." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Guwahati" -cities @(@{Name="Guwahati"; Nights="2 Nights"},@{Name="Shillong"; Nights="3 Nights"},@{Name="Cherrapunjee"; Nights="1 Night"}) -itinerary @(@{Title="Arrival at Guwahati"; Dest="Guwahati"; Content="Arrive at Guwahati airport. Check-in to your hotel. Visit Kamakhya Temple and enjoy an evening sunset cruise on the Brahmaputra River. Overnight in Guwahati."},@{Title="Guwahati to Shillong"; Dest="Shillong"; Content="Drive to Shillong. En route stop at Umiam Lake for scenic views. Check in at hotel in Shillong. Overnight stay."},@{Title="Day trip to Dawki Mawlynnong"; Dest="Shillong"; Content="Full day excursion to Mawlynnong and Dawki. Return to Shillong. Overnight stay."},@{Title="Shillong to Cherrapunjee"; Dest="Cherrapunjee"; Content="Drive to Cherrapunjee. Visit Elephant Falls, Shillong Peak, Nohkalikai Falls, Mawsmai Caves, and Seven Sisters Falls. Check into hotel. Overnight at Cherrapunjee."},@{Title="Cherrapunjee to Guwahati"; Dest="Guwahati"; Content="Morning at leisure or hike to the Double Decker Living Root Bridge. Later drive back to Guwahati. Overnight in Guwahati."},@{Title="Departure"; Dest="Guwahati"; Content="After breakfast, transfer to Guwahati airport/station for your onward journey."})

Generate-Package -filename "short-break-coorg-mysore.html" -title "Short Break to Coorg Mysore" -duration "4 Nights / 5 Days" -region "Karnataka" -places "Mysore, Coorg" -type "Wildlife Plantations" -bg "https://images.unsplash.com/photo-1623869680327-013baacf807e?w=1800" -overview "Escape to the coffee estates of Coorg, known as the Scotland of India, combined with the royal heritage of Mysore. A relaxing getaway packed with greenery, waterfalls, and cultural spectacles." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Bangalore" -cities @(@{Name="Mysore"; Nights="2 Nights"},@{Name="Coorg"; Nights="2 Nights"}) -itinerary @(@{Title="Bangalore to Mysore"; Dest="Mysore"; Content="Pick up from Bangalore. Drive to Mysore. Arrive in Mysore, check in, and visit the illuminated Brindavan Gardens in the evening. Overnight in Mysore."},@{Title="Mysore Sightseeing"; Dest="Mysore"; Content="After breakfast, visit the majestic Mysore Palace, Chamundi Hills, Nandi Bull, and St. Philomenas Church. Overnight in Mysore."},@{Title="Mysore to Coorg (Madikeri)"; Dest="Coorg"; Content="Drive to Coorg via the Tibetan settlement of Bylakuppe. Check in to the hotel in Madikeri. Evening at leisure. Overnight in Coorg."},@{Title="Coorg Sightseeing"; Dest="Coorg"; Content="Visit Abbey Falls, Omkareshwara Temple, Madikeri Fort, and Rajas Seat for a beautiful sunset viewing. Return to the hotel. Overnight in Coorg."},@{Title="Departure to Bangalore"; Dest="Bangalore"; Content="Check out and drive back to Bangalore for your drop off at the airport/station."})

Generate-Package -filename "himalayan-triangle.html" -title "The Himalayan Triangle" -duration "6 Nights / 7 Days" -region "Himachal Punjab" -places "Shimla, Manali, Chandigarh" -type "Mountains" -bg "https://images.unsplash.com/photo-1593693397690-362bb9a11863?w=1800" -overview "An extended trip covering the queen of hills, Shimla, the adventure hub of Manali, and the architectural wonder of Chandigarh. Enjoy snow points, historic sites, and amazing mountain passes." -price "On Request" -price_tax "Per Person on Twin Sharing Excl. 5% GST" -departing "Delhi / Chandigarh" -cities @(@{Name="Shimla"; Nights="2 Nights"},@{Name="Manali"; Nights="3 Nights"},@{Name="Chandigarh"; Nights="1 Night"}) -itinerary @(@{Title="Arrival Transfer to Shimla"; Dest="Shimla"; Content="Start your journey from Delhi/Chandigarh to Shimla. Check into your hotel. Evening walk on the Mall Road. Overnight in Shimla."},@{Title="Kufri Excursion"; Dest="Shimla"; Content="Full day excursion to Kufri for snow activities and local sights like Jakhoo Temple. Overnight in Shimla."},@{Title="Shimla to Manali"; Dest="Manali"; Content="Scenic drive to Manali via Kullu Valley. Stop at Kullu for shawl factories and optional river rafting. Check-in and overnight in Manali."},@{Title="Manali Local Sightseeing"; Dest="Manali"; Content="Visit Hadimba Temple, Vashisht Hot Springs, and Tibetan Monasteries. Evening free for Mall Road. Overnight in Manali."},@{Title="Solang Valley / Rohtang Pass"; Dest="Manali"; Content="Full day tour to Solang Valley for adventure sports or Rohtang Pass. Overnight in Manali."},@{Title="Manali to Chandigarh"; Dest="Chandigarh"; Content="Long drive back to the plains. Arrive in Chandigarh. Check-in and relax. Overnight in Chandigarh."},@{Title="Departure"; Dest="Chandigarh"; Content="Morning visit to the Rock Garden and Sukhna Lake. Later, transfer to Chandigarh airport/station or drive back to Delhi for drop-off."})
